### ISSUE TITLE
optimist or pesimist transaction

### ISSUE THREAD

**Issue by scwall** [MannikJ/laravel-wallet#11]
Hello, 
I came across your library by chance which is really nice :) . I was setting up the same thing but in your code I don't see any pessimistic or optimistic locks in the users' transactions. Or did I look at it wrong? 
Thank's for response

**Comment by scwall** [comment]
oh sorry I think I found public function replace($attributes)
```
{
        return \DB::transaction(function () use ($attributes) { 
```
Is it enough to use this system rather than a lockforupdate to make sure it is not used? Or do you use a unique id generator to find out if another process has modified the line concerned, because if the line that needs to be updated is used by another process while it is being used, there is no risk of having an update problem?? 
Thank's for response

**Comment by MannikJ** [comment]
Well actually there is no handling of race conditions etc. build into this package. If your application requires locking you will need to implement that yourself. 

The replace function above has been created for a quite special need inside our own app and it doesn't really care for logical concurrency issues as well. At least that was not its purpose.

Feel free to send pull requests if you have ideas how to ensure some better safety for concurrent transactions. I would like to improve this package, but I don't have the time to implement things that go beyond the functionality we need in our own app.

However, I would also encourage you to see if it makes sense for you to migrate to [this](https://github.com/bavix/laravel-wallet/issues) package instead of using ours, because it is way more popular and therefor better maintained.

**Comment by scwall** [comment]
Hello, thank you for your answer. 
I finally went for the solution you proposed.
 I don't have a lot of time to propose code updates at the moment.
  If I see some time coming, I will come to make some little pull requests again 
  thank you for your answer on the closed message.
